### ISSUE TITLE
https://github.com/AuthorityWang/NeuS2_K/

### ISSUE THREAD

**Issue by zihanzheng-sjtu** [AuthorityWang/VideoGS#1]
Thank you for your wonderful work! I find that https://github.com/AuthorityWang/NeuS2_K.git can not be found now. Could you please give me some advice?

**Comment by AuthorityWang** [comment]
Hi, this has been made public now.

**Comment by zihanzheng-sjtu** [comment]
Thank you for your quick reply. I will try it.
