### ISSUE TITLE
CUDA OutofMemory after the decompression process 

### ISSUE THREAD

**Issue by zihanzheng-sjtu** [AuthorityWang/VideoGS#4]
Hello, I have another question. During the rendering process of the PLY file obtained after compression by `compress_ckpt_2_image_precompute.py`, `compress_image_2_video.py` and decompression by `decompress_video_2_ckpt.py`, I encountered a GPU memory explosion issue. Do you have any ideas on what might be causing this?
![截图 2024-12-04 15-20-55](https://github.com/user-attachments/assets/189b4f5d-82f8-42fe-a550-1f05e739f1d4)

**Comment by zihanzheng-sjtu** [comment]
I have found out what's wrong. I should run `compress_ckpt_2_image.py` instead of `compress_ckpt_2_image_precompute.py`

**Comment by gshhher** [comment]
![微信图片_20241210220136](https://github.com/user-attachments/assets/cf1b2681-7274-4235-9811-11c39d9d39a4)

**Comment by gshhher** [comment]
![微信图片_20241210220136](https://github.com/user-attachments/assets/07c10820-6c17-421c-b325-72190f8ecab0)
Have you meet the same wrong?I don't not know why ,I use the HiFi4G ,and the point3d.obj is empty.
