### ISSUE TITLE
data structure for train_dynamic.py on custom datasets

### ISSUE THREAD

**Issue by henrypearce4D** [AuthorityWang/VideoGS#5]
Very impressed with the demos of this code.

I cannot access the datasets, so I cannot test the code properly to see and understand the data structure clearly.

I would like to test running the train_dynamic.py on our sequence of .ply files.

What is the folder structure needed? what other corresponding files does the script need to run?

**Comment by AuthorityWang** [comment]
Hi, sorry for late response. 
The train_dynamic.py takes multi-frame multi-view images as input, you can refer to the `Format` in `Dataset Preprocess` of `README.md`, which is 
```
datasets
|   |---xxx (data name)
|   |   |---%d
|   |   |   |---images
|   |   |   |   |---%d.png
|   |   |   |---transforms.json
```
If you already have gaussian-splatting ply sequences, you can test the compression follow the  `Compression` in `README.md`.

**Comment by henrypearce4D** [comment]
Does running just the train_dynamic.py also train the sequence if I am providing just the images and transforms.json?

Our sequence of .ply is not temporally consistent, it was trained as a per frame gaussian splat, hence my interest of running train_dynamic.py on the sequence of .ply not from scratch.

**Comment by AuthorityWang** [comment]
Just Running the train_dynamic.py with images and transforms.json will train from scratch. As your sequence of .ply is not temporally consistent and is trained as per-frame, I'm afraid that it could not be initialization of our method, as our method need strong termporal consistent and point correspondence. 

However, as our method split the sequence with 20 frames as a group, and train the first frame of each group with gaussian splat, you can use your sequence ply as each group's first frame. So for each group, you only need to train the rest 19 frames, which corresponds to line94 - line96 in train_dynamic.py

**Comment by henrypearce4D** [comment]
Are we able to use our colmap model files for each frame instead of Neus2 ?

We have per frame;
cameras.bin
images.bin
points3d.bin

The points3d.bin is unique to each frame.

**Comment by AuthorityWang** [comment]
Yes, the point cloud from NeuS2 mesh provides an initialization for 3DGS, so the Colmap point cloud also works.

**Comment by moqiyinlun** [comment]
You can access https://github.com/moqiyinlun/HiFi4G_Dataset and https://github.com/xyi1023/DualGS_Dataset to get part of the data. The datasets are publicly accessible now.
