### ISSUE TITLE
about dataset and training

### ISSUE THREAD

**Issue by gshhher** [AuthorityWang/VideoGS#6]
I want to know whether the input passed to the training is the file path of the processed dataset mentioned above.

**Comment by gshhher** [comment]
Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1497/1500 [00:34<00:00, 44.00step/s, loss=0.000472]
Generating mesh via marching cubes and saving to /home/gsh/VideoGS/output/Clothes/neus2_output/0/points3d.obj. Resolution=[500,500,500]
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/gsh/VideoGS/train_sequence.py", line 73, in <module>
    ms.load_new_mesh(frame_neus2_mesh_output_path)
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/gsh/VideoGS/output/Clothes/neus2_output/0/points3d.obj
Error encountered while loading file:
"points3d.obj"

Error details: No vertex found,
why

**Comment by AuthorityWang** [comment]
Seems that the sampled point cloud from the mesh has no vertex. I noticed that there is a segmentation fault during the performing of the marching cube, so maybe it's a problem related to NeuS2. Can you provide more details about the platform you used?

**Comment by gshhher** [comment]
> 似乎从网格中采样的点云没有顶点。我注意到在执行行进立方体时存在分段错误，因此可能与 NeuS2 有关。您能否提供有关您使用的平台的更多详细信息？

Thank you for your reply, I have solved this problem, it was an issue when I compiled NeuS2, I can train normally after recompiling, thank you very much.
