### ISSUE TITLE
training wrong

### ISSUE THREAD

**Issue by gshhher** [AuthorityWang/VideoGS#7]
I use the HIFI4G dataset ,and process, but why i train wrong , and the point3d is empty

**Comment by AuthorityWang** [comment]
The empty point3d is related to the NeuS2, can you provide more details about the training platform you used?

**Comment by gshhher** [comment]
> The empty point3d is related to the NeuS2, can you provide more details about the training platform you used?

Thank you for your reply, I have solved this problem, it was an issue when I compiled NeuS2, I can train normally after recompiling, thank you very much.
